apiVersion: v1
baseDomain: {{ domain }}
compute:
- name: worker
  replicas: {{ workers }}
controlPlane:
  name: master
  replicas: {{ masters }}
metadata:
  name: {{ cluster }}
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 192.168.122.0/24
  serviceNetwork:
  - 172.30.0.0/16
  networkType: {{ network_type }}
platform:
{%- if config_type == 'vsphere' %}
  vsphere:
    vcenter: {{ config_host }}
    username: {{ config_user }}
    password: {{ config_password }}
    datacenter: {{ config_datacenter }}
    defaultDatastore: {{ config_pool }}
{%- else %}
  none: {}
{%- endif %}
pullSecret: '{{ pull_secret }}'
sshKey: |
  {{ pub_key }}
